authors        = ["sebcode"]
description    = "Psalm support for Zed"
id             = "psalm"
name           = "Psalm"
repository     = "https://github.com/sebcode/psalm-zed"
schema_version = 1
version        = "0.0.1"

[language_servers.psalm]
language          = "PHP"
languages         = ["PHP"]
name              = "Psalm Language Server"
